// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockPostgresDumper is an autogenerated mock type for the PostgresDumper type
type MockPostgresDumper struct {
	mock.Mock
}

type MockPostgresDumper_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPostgresDumper) EXPECT() *MockPostgresDumper_Expecter {
	return &MockPostgresDumper_Expecter{mock: &_m.Mock}
}

// Dump provides a mock function with given fields: ctx, dest
func (_m *MockPostgresDumper) Dump(ctx context.Context, dest string) error {
	ret := _m.Called(ctx, dest)

	if len(ret) == 0 {
		panic("no return value specified for Dump")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, dest)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockPostgresDumper_Dump_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Dump'
type MockPostgresDumper_Dump_Call struct {
	*mock.Call
}

// Dump is a helper method to define mock.On call
//   - ctx context.Context
//   - dest string
func (_e *MockPostgresDumper_Expecter) Dump(ctx interface{}, dest interface{}) *MockPostgresDumper_Dump_Call {
	return &MockPostgresDumper_Dump_Call{Call: _e.mock.On("Dump", ctx, dest)}
}

func (_c *MockPostgresDumper_Dump_Call) Run(run func(ctx context.Context, dest string)) *MockPostgresDumper_Dump_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockPostgresDumper_Dump_Call) Return(_a0 error) *MockPostgresDumper_Dump_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPostgresDumper_Dump_Call) RunAndReturn(run func(context.Context, string) error) *MockPostgresDumper_Dump_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPostgresDumper creates a new instance of MockPostgresDumper. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPostgresDumper(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPostgresDumper {
	mock := &MockPostgresDumper{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
