// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockMongoDumper is an autogenerated mock type for the MongoDumper type
type MockMongoDumper struct {
	mock.Mock
}

type MockMongoDumper_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMongoDumper) EXPECT() *MockMongoDumper_Expecter {
	return &MockMongoDumper_Expecter{mock: &_m.Mock}
}

// Dump provides a mock function with given fields: ctx, dumpDir
func (_m *MockMongoDumper) Dump(ctx context.Context, dumpDir string) error {
	ret := _m.Called(ctx, dumpDir)

	if len(ret) == 0 {
		panic("no return value specified for Dump")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, dumpDir)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockMongoDumper_Dump_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Dump'
type MockMongoDumper_Dump_Call struct {
	*mock.Call
}

// Dump is a helper method to define mock.On call
//   - ctx context.Context
//   - dumpDir string
func (_e *MockMongoDumper_Expecter) Dump(ctx interface{}, dumpDir interface{}) *MockMongoDumper_Dump_Call {
	return &MockMongoDumper_Dump_Call{Call: _e.mock.On("Dump", ctx, dumpDir)}
}

func (_c *MockMongoDumper_Dump_Call) Run(run func(ctx context.Context, dumpDir string)) *MockMongoDumper_Dump_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockMongoDumper_Dump_Call) Return(_a0 error) *MockMongoDumper_Dump_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMongoDumper_Dump_Call) RunAndReturn(run func(context.Context, string) error) *MockMongoDumper_Dump_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockMongoDumper creates a new instance of MockMongoDumper. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMongoDumper(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMongoDumper {
	mock := &MockMongoDumper{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
