// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	port "github.com/Sargastico/rclonarr/internal/core/domain/port"
	mock "github.com/stretchr/testify/mock"
)

// MockRemoteUploader is an autogenerated mock type for the RemoteUploader type
type MockRemoteUploader struct {
	mock.Mock
}

type MockRemoteUploader_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRemoteUploader) EXPECT() *MockRemoteUploader_Expecter {
	return &MockRemoteUploader_Expecter{mock: &_m.Mock}
}

// EnsureAuth provides a mock function with given fields: ctx
func (_m *MockRemoteUploader) EnsureAuth(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for EnsureAuth")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRemoteUploader_EnsureAuth_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnsureAuth'
type MockRemoteUploader_EnsureAuth_Call struct {
	*mock.Call
}

// EnsureAuth is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockRemoteUploader_Expecter) EnsureAuth(ctx interface{}) *MockRemoteUploader_EnsureAuth_Call {
	return &MockRemoteUploader_EnsureAuth_Call{Call: _e.mock.On("EnsureAuth", ctx)}
}

func (_c *MockRemoteUploader_EnsureAuth_Call) Run(run func(ctx context.Context)) *MockRemoteUploader_EnsureAuth_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockRemoteUploader_EnsureAuth_Call) Return(_a0 error) *MockRemoteUploader_EnsureAuth_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRemoteUploader_EnsureAuth_Call) RunAndReturn(run func(context.Context) error) *MockRemoteUploader_EnsureAuth_Call {
	_c.Call.Return(run)
	return _c
}

// ListFiles provides a mock function with given fields: ctx, remoteDir
func (_m *MockRemoteUploader) ListFiles(ctx context.Context, remoteDir string) ([]port.RemoteFile, error) {
	ret := _m.Called(ctx, remoteDir)

	if len(ret) == 0 {
		panic("no return value specified for ListFiles")
	}

	var r0 []port.RemoteFile
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]port.RemoteFile, error)); ok {
		return rf(ctx, remoteDir)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []port.RemoteFile); ok {
		r0 = rf(ctx, remoteDir)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]port.RemoteFile)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, remoteDir)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRemoteUploader_ListFiles_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListFiles'
type MockRemoteUploader_ListFiles_Call struct {
	*mock.Call
}

// ListFiles is a helper method to define mock.On call
//   - ctx context.Context
//   - remoteDir string
func (_e *MockRemoteUploader_Expecter) ListFiles(ctx interface{}, remoteDir interface{}) *MockRemoteUploader_ListFiles_Call {
	return &MockRemoteUploader_ListFiles_Call{Call: _e.mock.On("ListFiles", ctx, remoteDir)}
}

func (_c *MockRemoteUploader_ListFiles_Call) Run(run func(ctx context.Context, remoteDir string)) *MockRemoteUploader_ListFiles_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRemoteUploader_ListFiles_Call) Return(_a0 []port.RemoteFile, _a1 error) *MockRemoteUploader_ListFiles_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRemoteUploader_ListFiles_Call) RunAndReturn(run func(context.Context, string) ([]port.RemoteFile, error)) *MockRemoteUploader_ListFiles_Call {
	_c.Call.Return(run)
	return _c
}

// Trash provides a mock function with given fields: ctx, remotePaths
func (_m *MockRemoteUploader) Trash(ctx context.Context, remotePaths ...string) error {
	_va := make([]interface{}, len(remotePaths))
	for _i := range remotePaths {
		_va[_i] = remotePaths[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Trash")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, ...string) error); ok {
		r0 = rf(ctx, remotePaths...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRemoteUploader_Trash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Trash'
type MockRemoteUploader_Trash_Call struct {
	*mock.Call
}

// Trash is a helper method to define mock.On call
//   - ctx context.Context
//   - remotePaths ...string
func (_e *MockRemoteUploader_Expecter) Trash(ctx interface{}, remotePaths ...interface{}) *MockRemoteUploader_Trash_Call {
	return &MockRemoteUploader_Trash_Call{Call: _e.mock.On("Trash",
		append([]interface{}{ctx}, remotePaths...)...)}
}

func (_c *MockRemoteUploader_Trash_Call) Run(run func(ctx context.Context, remotePaths ...string)) *MockRemoteUploader_Trash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]string, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(string)
			}
		}
		run(args[0].(context.Context), variadicArgs...)
	})
	return _c
}

func (_c *MockRemoteUploader_Trash_Call) Return(_a0 error) *MockRemoteUploader_Trash_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRemoteUploader_Trash_Call) RunAndReturn(run func(context.Context, ...string) error) *MockRemoteUploader_Trash_Call {
	_c.Call.Return(run)
	return _c
}

// Upload provides a mock function with given fields: ctx, localPath, remoteDir
func (_m *MockRemoteUploader) Upload(ctx context.Context, localPath string, remoteDir string) error {
	ret := _m.Called(ctx, localPath, remoteDir)

	if len(ret) == 0 {
		panic("no return value specified for Upload")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, localPath, remoteDir)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRemoteUploader_Upload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Upload'
type MockRemoteUploader_Upload_Call struct {
	*mock.Call
}

// Upload is a helper method to define mock.On call
//   - ctx context.Context
//   - localPath string
//   - remoteDir string
func (_e *MockRemoteUploader_Expecter) Upload(ctx interface{}, localPath interface{}, remoteDir interface{}) *MockRemoteUploader_Upload_Call {
	return &MockRemoteUploader_Upload_Call{Call: _e.mock.On("Upload", ctx, localPath, remoteDir)}
}

func (_c *MockRemoteUploader_Upload_Call) Run(run func(ctx context.Context, localPath string, remoteDir string)) *MockRemoteUploader_Upload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockRemoteUploader_Upload_Call) Return(_a0 error) *MockRemoteUploader_Upload_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRemoteUploader_Upload_Call) RunAndReturn(run func(context.Context, string, string) error) *MockRemoteUploader_Upload_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRemoteUploader creates a new instance of MockRemoteUploader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRemoteUploader(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRemoteUploader {
	mock := &MockRemoteUploader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
