// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	models "github.com/Sargastico/rclonarr/internal/core/domain/models"
	mock "github.com/stretchr/testify/mock"
)

// MockTargetRegistry is an autogenerated mock type for the TargetRegistry type
type MockTargetRegistry struct {
	mock.Mock
}

type MockTargetRegistry_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTargetRegistry) EXPECT() *MockTargetRegistry_Expecter {
	return &MockTargetRegistry_Expecter{mock: &_m.Mock}
}

// EnabledTargets provides a mock function with no fields
func (_m *MockTargetRegistry) EnabledTargets() ([]models.BackupTarget, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for EnabledTargets")
	}

	var r0 []models.BackupTarget
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]models.BackupTarget, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []models.BackupTarget); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.BackupTarget)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTargetRegistry_EnabledTargets_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnabledTargets'
type MockTargetRegistry_EnabledTargets_Call struct {
	*mock.Call
}

// EnabledTargets is a helper method to define mock.On call
func (_e *MockTargetRegistry_Expecter) EnabledTargets() *MockTargetRegistry_EnabledTargets_Call {
	return &MockTargetRegistry_EnabledTargets_Call{Call: _e.mock.On("EnabledTargets")}
}

func (_c *MockTargetRegistry_EnabledTargets_Call) Run(run func()) *MockTargetRegistry_EnabledTargets_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTargetRegistry_EnabledTargets_Call) Return(_a0 []models.BackupTarget, _a1 error) *MockTargetRegistry_EnabledTargets_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTargetRegistry_EnabledTargets_Call) RunAndReturn(run func() ([]models.BackupTarget, error)) *MockTargetRegistry_EnabledTargets_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTargetRegistry creates a new instance of MockTargetRegistry. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTargetRegistry(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTargetRegistry {
	mock := &MockTargetRegistry{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
