// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/Sargastico/rclonarr/internal/core/domain/models"
	mock "github.com/stretchr/testify/mock"
)

// MockArrBackupTrigger is an autogenerated mock type for the ArrBackupTrigger type
type MockArrBackupTrigger struct {
	mock.Mock
}

type MockArrBackupTrigger_Expecter struct {
	mock *mock.Mock
}

func (_m *MockArrBackupTrigger) EXPECT() *MockArrBackupTrigger_Expecter {
	return &MockArrBackupTrigger_Expecter{mock: &_m.Mock}
}

// Trigger provides a mock function with given fields: ctx, target
func (_m *MockArrBackupTrigger) Trigger(ctx context.Context, target models.BackupTarget) (string, error) {
	ret := _m.Called(ctx, target)

	if len(ret) == 0 {
		panic("no return value specified for Trigger")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, models.BackupTarget) (string, error)); ok {
		return rf(ctx, target)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.BackupTarget) string); ok {
		r0 = rf(ctx, target)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.BackupTarget) error); ok {
		r1 = rf(ctx, target)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockArrBackupTrigger_Trigger_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Trigger'
type MockArrBackupTrigger_Trigger_Call struct {
	*mock.Call
}

// Trigger is a helper method to define mock.On call
//   - ctx context.Context
//   - target models.BackupTarget
func (_e *MockArrBackupTrigger_Expecter) Trigger(ctx interface{}, target interface{}) *MockArrBackupTrigger_Trigger_Call {
	return &MockArrBackupTrigger_Trigger_Call{Call: _e.mock.On("Trigger", ctx, target)}
}

func (_c *MockArrBackupTrigger_Trigger_Call) Run(run func(ctx context.Context, target models.BackupTarget)) *MockArrBackupTrigger_Trigger_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(models.BackupTarget))
	})
	return _c
}

func (_c *MockArrBackupTrigger_Trigger_Call) Return(localBackupPath string, err error) *MockArrBackupTrigger_Trigger_Call {
	_c.Call.Return(localBackupPath, err)
	return _c
}

func (_c *MockArrBackupTrigger_Trigger_Call) RunAndReturn(run func(context.Context, models.BackupTarget) (string, error)) *MockArrBackupTrigger_Trigger_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockArrBackupTrigger creates a new instance of MockArrBackupTrigger. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockArrBackupTrigger(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockArrBackupTrigger {
	mock := &MockArrBackupTrigger{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
