// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockRcloneSyncer is an autogenerated mock type for the RcloneSyncer type
type MockRcloneSyncer struct {
	mock.Mock
}

type MockRcloneSyncer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRcloneSyncer) EXPECT() *MockRcloneSyncer_Expecter {
	return &MockRcloneSyncer_Expecter{mock: &_m.Mock}
}

// Copy provides a mock function with given fields: ctx, localPath, remotePath
func (_m *MockRcloneSyncer) Copy(ctx context.Context, localPath string, remotePath string) error {
	ret := _m.Called(ctx, localPath, remotePath)

	if len(ret) == 0 {
		panic("no return value specified for Copy")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, localPath, remotePath)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRcloneSyncer_Copy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Copy'
type MockRcloneSyncer_Copy_Call struct {
	*mock.Call
}

// Copy is a helper method to define mock.On call
//   - ctx context.Context
//   - localPath string
//   - remotePath string
func (_e *MockRcloneSyncer_Expecter) Copy(ctx interface{}, localPath interface{}, remotePath interface{}) *MockRcloneSyncer_Copy_Call {
	return &MockRcloneSyncer_Copy_Call{Call: _e.mock.On("Copy", ctx, localPath, remotePath)}
}

func (_c *MockRcloneSyncer_Copy_Call) Run(run func(ctx context.Context, localPath string, remotePath string)) *MockRcloneSyncer_Copy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockRcloneSyncer_Copy_Call) Return(_a0 error) *MockRcloneSyncer_Copy_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRcloneSyncer_Copy_Call) RunAndReturn(run func(context.Context, string, string) error) *MockRcloneSyncer_Copy_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRcloneSyncer creates a new instance of MockRcloneSyncer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRcloneSyncer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRcloneSyncer {
	mock := &MockRcloneSyncer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
